spring:
  application:
  name: robot-agent
  datasource:
    url: jdbc:sqlite:robot.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

logging:
  level:
    root: INFO
    com.robot.agent: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

mqtt:
  broker: tcp://localhost:1883
  client-id: RobotAgent_${random.uuid}
  connection-timeout: 10
  keep-alive-interval: 60

ros2:
  publishers: /turtle1/cmd_vel, /robot/telemetry
  subscribers: /turtle1/pose, /robot/commands
