spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: robot-agent
  datasource:
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

logging:
  level:
    root: INFO
    com.robot.agent: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

mqtt:
  broker-url: ${MQTT_BROKER_URL:localhost}
  port: 1883
  client-id: RobotAgent
  connection-timeout: 10
  keep-alive-interval: 60

ros2:
  publishers: /turtle1/cmd_vel, /robot/telemetry
  subscribers: /turtle1/pose, /robot/commands

---
# Local development profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:sqlite:robot.db

---
# Docker profile
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:sqlite:/app/data/robot.db